#!/bin/bash

echo "========================================="
echo "✅ SYSTEM READY - COMPLETE TEST GUIDE"
echo "========================================="
echo ""

GW="http://localhost:4000"

echo "📊 BACKEND SERVICES STATUS"
echo "--------------------------"
curl -s "$GW/rooms/health" > /dev/null && echo "✓ Rooms Service (4001)" || echo "✗ Rooms down"
curl -s "$GW/services/health" > /dev/null && echo "✓ Services API (4002)" || echo "✗ Services down"
curl -s "$GW/movies/health" > /dev/null && echo "✓ Movies Service (4005)" || echo "✗ Movies down"
curl -s "$GW/venues/health" > /dev/null && echo "✓ Venues Service (4007)" || echo "✗ Venues down"
curl -s "$GW/finance/health" > /dev/null && echo "✓ Finance Bridge (4004)" || echo "✗ Finance down"

echo ""
echo "🎨 FRONTEND ACCESS"
echo "------------------"
echo "Vendor Admin: http://localhost:5184/vendor/"
echo "User Portal:  http://localhost:5183/user/"
echo ""

echo "📦 DEMO DATA AVAILABLE"
echo "----------------------"
PGPASSWORD=postgres psql -h localhost -U postgres -d mangwale_booking -t -A -c "
SELECT '✓ ' || COUNT(*) || ' Room Types' FROM room_types
UNION ALL SELECT '✓ ' || COUNT(*) || ' Services' FROM services_catalog
UNION ALL SELECT '✓ ' || COUNT(*) || ' Movies' FROM movies
UNION ALL SELECT '✓ ' || COUNT(*) || ' Venues' FROM venue_types
UNION ALL SELECT '✓ ' || COUNT(*) || ' Service Slots' FROM service_slots
UNION ALL SELECT '✓ ' || COUNT(*) || ' Movie Showtimes' FROM showtimes
UNION ALL SELECT '✓ ' || COUNT(*) || ' Venue Slots' FROM venue_slots;
" 2>/dev/null

echo ""
echo "🧪 QUICK API TESTS"
echo "------------------"

# Test each module
test_count() {
  local name=$1
  local url=$2
  local count=$(curl -s "$url" 2>/dev/null | jq -r 'if type=="array" then length else 0 end' 2>/dev/null || echo "0")
  if [ "$count" != "0" ]; then
    echo "✓ $name: $count items"
  else
    echo "✗ $name: Failed"
  fi
}

test_count "Room Types    " "$GW/rooms/vendor/rooms/room-types"
test_count "Services      " "$GW/services/vendor/services/catalog"
test_count "Movies        " "$GW/movies/vendor/movies/catalog"
test_count "Venues        " "$GW/venues/vendor/venues/catalog"

echo ""
echo "========================================="
echo "🎯 HOW TO TEST"
echo "========================================="
echo ""
echo "VENDOR ADMIN (http://localhost:5184/vendor/)"
echo "---------------------------------------------"
echo "1. Create a Service:"
echo "   - Name: \"Deep Tissue Massage\""
echo "   - Category: spa"
echo "   - Base Price: 100, Visit Fee: 20"
echo "   - Click 'Add Service'"
echo ""
echo "2. Create a Service Slot:"
echo "   - Date: 2026-03-15"
echo "   - Time: 10:00 - 12:00"
echo "   - Capacity: 5"
echo "   - Click 'Add Slot'"
echo ""
echo "3. View existing data:"
echo "   - See 4 room types, 8 services, 9 movies, 4 venues"
echo "   - Scroll to bottom to see 'Current Bookings'"
echo ""
echo "USER PORTAL (http://localhost:5183/user/)"
echo "------------------------------------------"
echo "1. Browse Services:"
echo "   - See list of 8+ services"
echo "   - Click 'Book' on any service"
echo "   - Select a slot"
echo "   - Fill form & submit"
echo ""
echo "2. Browse Movies:"
echo "   - See 9+ movies with showtimes"
echo "   - Click 'Book' on a showtime"
echo "   - Select seats (click on seat grid)"
echo "   - Submit booking"
echo ""
echo "3. Browse Venues:"
echo "   - See 4+ venue types"
echo "   - Click 'Book' on a venue"
echo "   - Select date & hours"
echo "   - Submit booking"
echo ""
echo "4. Browse Rooms:"
echo "   - Enter check-in/out dates"
echo "   - Click 'Search'"
echo "   - Select room & rate plan"
echo "   - Submit booking"
echo ""
echo "========================================="
echo "📋 TESTING CHECKLIST"
echo "========================================="
echo ""
echo "[ ] Open Vendor Admin - page loads"
echo "[ ] See demo data populated"
echo "[ ] Create a new service"
echo "[ ] Create a new service slot"
echo "[ ] Open User Portal - page loads"
echo "[ ] Browse services - see list"
echo "[ ] Book a service - success"
echo "[ ] Browse movies - see list"
echo "[ ] Book movie seats - success"
echo "[ ] Browse venues - see list"
echo "[ ] Book a venue - success"
echo "[ ] Browse rooms - see available rooms"
echo "[ ] Book a room - success"
echo "[ ] Go back to Vendor Admin"
echo "[ ] See new bookings in 'Current Bookings'"
echo ""
echo "========================================="
echo "🔧 USEFUL COMMANDS"
echo "========================================="
echo ""
echo "# Check booking in database:"
echo "PGPASSWORD=postgres psql -h localhost -U postgres -d mangwale_booking \\"
echo "  -c \"SELECT * FROM service_appointments ORDER BY id DESC LIMIT 5;\""
echo ""
echo "# Test booking API directly:"
echo "curl -X POST $GW/services/appointments \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"userId\": 101,"
echo "    \"storeId\": 201,"
echo "    \"serviceId\": 1,"
echo "    \"scheduledFor\": \"2026-03-15T10:00:00Z\","
echo "    \"slotId\": 1,"
echo "    \"pricing\": {\"baseMinor\": 5000, \"visitFeeMinor\": 1000},"
echo "    \"payment\": {\"mode\": \"prepaid\", \"idempotencyKey\": \"test-\$(date +%s)\"}"
echo "  }'"
echo ""
echo "========================================="
echo "✨ ALL READY! Start testing above ↑"
echo "========================================="
